### ISSUE TITLE
TODO MVP

### ISSUE THREAD

**Issue by johntyree** [open-austin/austingreenmap#1]
- [x] Index/List of json files by id / location / proximity
  - [x] Park ID
  - [x] Park Name
  - [x] Coordinates
  - [ ] Neighborhood
- [ ] Map appropriate amenity/facility icon markers to classifications in json
- [x] List view of the things on the map (park, amenity, facility)
- [x] Detail view of icons
- [x] Filters
  - Neighborhood?
  - Activity
  - Amenity/Facility

**Comment by luqmaan** [comment]
We have most of these done. Closing this issue.

:deciduous_tree:
